"""
Plot training curves from CSV logs generated by train.py.
Reads models/{backbone}_training_log.csv for each backbone.
Outputs: report/figures/training_curves/*.pdf
"""

import os
import csv
import numpy as np

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ─── Config ───────────────────────────────────────────────────────────────────

MODELS_DIR = "models"
OUTPUT_DIR = "report/figures/training_curves"
BACKBONES  = ["resnet18", "efficientnet_b0", "vgg16", "inception_v3", "mobilenet_v3"]

BACKBONE_LABELS = {
    "resnet18":        "ResNet-18",
    "efficientnet_b0": "EfficientNet-B0",
    "vgg16":           "VGG-16",
    "inception_v3":    "Inception v3",
    "mobilenet_v3":    "MobileNet v3",
}

# Nice color palette
COLORS = {
    "resnet18":        "#2196F3",
    "efficientnet_b0": "#4CAF50",
    "vgg16":           "#FF9800",
    "inception_v3":    "#E91E63",
    "mobilenet_v3":    "#9C27B0",
}

os.makedirs(OUTPUT_DIR, exist_ok=True)

plt.rcParams.update({
    "font.family": "serif",
    "font.size": 10,
    "axes.grid": True,
    "grid.alpha": 0.3,
    "figure.dpi": 150,
})

# ─── Load data ────────────────────────────────────────────────────────────────

def load_csv(backbone):
    """Load training log CSV for a given backbone."""
    path = os.path.join(MODELS_DIR, f"{backbone}_training_log.csv")
    if not os.path.exists(path):
        print(f"  CSV not found: {path}")
        return None

    data = {"epoch": [], "train_loss": [], "train_mae": [], "train_mse": [],
            "train_rmse": [], "train_acc": [],
            "val_loss": [], "val_mae": [], "val_mse": [],
            "val_rmse": [], "val_acc": []}
    with open(path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            data["epoch"].append(int(row["epoch"]))
            data["train_loss"].append(float(row["train_loss"]))
            data["train_mae"].append(float(row["train_mae"]))
            data["train_mse"].append(float(row["train_mse"]))
            data["train_rmse"].append(float(row["train_rmse"]))
            data["train_acc"].append(float(row["train_acc"]))
            data["val_loss"].append(float(row["val_loss"]))
            data["val_mae"].append(float(row["val_mae"]))
            data["val_mse"].append(float(row["val_mse"]))
            data["val_rmse"].append(float(row["val_rmse"]))
            data["val_acc"].append(float(row["val_acc"]))

    for k in data:
        data[k] = np.array(data[k])
    return data


# ─── Per-backbone plots ──────────────────────────────────────────────────────

def plot_per_backbone(backbone, data):
    """Five-subplot figure: Loss, MAE, MSE, RMSE, Accuracy — train vs val."""
    label = BACKBONE_LABELS.get(backbone, backbone)

    metrics = [
        ("train_loss", "val_loss", "Huber Loss", "Loss"),
        ("train_mae",  "val_mae",  "MAE",        "MAE"),
        ("train_mse",  "val_mse",  "MSE",        "MSE"),
        ("train_rmse", "val_rmse", "RMSE",       "RMSE"),
        ("train_acc",  "val_acc",  "Accuracy",   "Acc"),
    ]

    fig, axes = plt.subplots(1, 5, figsize=(22, 4))
    fig.suptitle(f"{label} — Training Curves", fontsize=14, fontweight="bold")

    for ax, (train_key, val_key, ylabel, title) in zip(axes, metrics):
        train_vals = data[train_key] * 100 if "acc" in train_key else data[train_key]
        val_vals   = data[val_key] * 100   if "acc" in val_key   else data[val_key]

        ax.plot(data["epoch"], train_vals, label="Train", color="#2196F3", linewidth=1.5)
        ax.plot(data["epoch"], val_vals,   label="Val",   color="#E91E63", linewidth=1.5)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(f"{ylabel} (%)" if "acc" in train_key else ylabel)
        ax.set_title(title)
        ax.legend(fontsize=8)

    plt.tight_layout(rect=[0, 0, 1, 0.93])
    out_path = os.path.join(OUTPUT_DIR, f"{backbone}_curves.pdf")
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)
    print(f"  ✓ {out_path}")


# ─── Comparison plots (separate per metric) ──────────────────────────────────

def plot_comparison(all_data):
    """Separate comparison plots: one per validation metric."""

    val_metrics = [
        ("val_loss", "Huber Loss", "Validation Loss"),
        ("val_mae",  "MAE",        "Validation MAE"),
        ("val_mse",  "MSE",        "Validation MSE"),
        ("val_rmse", "RMSE",       "Validation RMSE"),
        ("val_acc",  "Accuracy (%)", "Validation Accuracy"),
    ]

    # ── Individual comparison plots ──
    for key, ylabel, title in val_metrics:
        fig, ax = plt.subplots(figsize=(7, 4))
        for backbone, data in all_data.items():
            label = BACKBONE_LABELS.get(backbone, backbone)
            color = COLORS.get(backbone, "#000000")
            vals = data[key] * 100 if "acc" in key else data[key]
            ax.plot(data["epoch"], vals, label=label, color=color, linewidth=1.5)

        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.legend(fontsize=9)
        plt.tight_layout()

        safe_name = key.replace("val_", "")
        out_path = os.path.join(OUTPUT_DIR, f"comparison_{safe_name}.pdf")
        fig.savefig(out_path, bbox_inches="tight")
        plt.close(fig)
        print(f"  ✓ {out_path}")

    # ── Combined 2x2+1 comparison plot (all val metrics on one figure) ──
    fig, axes = plt.subplots(2, 3, figsize=(16, 8))
    axes_flat = axes.flatten()

    for i, (key, ylabel, title) in enumerate(val_metrics):
        ax = axes_flat[i]
        for backbone, data in all_data.items():
            label = BACKBONE_LABELS.get(backbone, backbone)
            color = COLORS.get(backbone, "#000000")
            vals = data[key] * 100 if "acc" in key else data[key]
            ax.plot(data["epoch"], vals, label=label, color=color, linewidth=1.5)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.legend(fontsize=7)

    # hide the 6th subplot (2x3 grid, only 5 metrics)
    axes_flat[5].set_visible(False)

    fig.suptitle("Validation Metrics — All Backbones", fontsize=14, fontweight="bold")
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    out_path = os.path.join(OUTPUT_DIR, "comparison_all.pdf")
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)
    print(f"  ✓ {out_path}")


# ─── Main ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    all_data = {}

    for backbone in BACKBONES:
        data = load_csv(backbone)
        if data is not None:
            all_data[backbone] = data
            plot_per_backbone(backbone, data)

    if all_data:
        plot_comparison(all_data)
        print(f"\n✓ All plots saved to {OUTPUT_DIR}/")
    else:
        print("\n✗ No training logs found. Run train.py first (delete existing .pth files to retrain).")
